<?php
return [
    'ab' => ['name' => 'Абхазский', 'native' => 'Аԥсшәа'],
    'av' => ['name' => 'Аварский', 'native' => 'Avaric'],
    'ae' => ['name' => 'Авестийский', 'native' => 'Avestan'],
    'az' => ['name' => 'Азербайджанский', 'native' => 'Azərbaycan'],
    'ay' => ['name' => 'Аймара', 'native' => 'Aymara'],
    'ak' => ['name' => 'Акан', 'native' => 'Akan'],
    'sq' => ['name' => 'Албанский', 'native' => 'Shqip'],
    'am' => ['name' => 'Амхарский', 'native' => 'አማርኛ'],
    'en' => ['name' => 'Английский', 'native' => 'English'],
    'ar' => ['name' => 'Арабский', 'native' => 'العربية'],
    'an' => ['name' => 'Арагонский', 'native' => 'Aragonés'],
    'hy' => ['name' => 'Армянский', 'native' => 'Հայերեն'],
    'as' => ['name' => 'Ассамский', 'native' => 'অসমীয়া'],
    'aa' => ['name' => 'Афарский', 'native' => 'Qafar'],
    'af' => ['name' => 'Африкаанс', 'native' => 'Afrikaans'],
    'bm' => ['name' => 'Бамбара', 'native' => 'Bamanakan'],
    'eu' => ['name' => 'Баскский', 'native' => 'Euskara'],
    'ba' => ['name' => 'Башкирский', 'native' => 'Башҡорт теле'],
    'be' => ['name' => 'Белорусский', 'native' => 'Беларуская'],
    'bn' => ['name' => 'Бенгальский', 'native' => 'বাংলা'],
    'my' => ['name' => 'Бирманский', 'native' => 'မြန်မာ'],
    'bi' => ['name' => 'Бислама', 'native' => 'Bislama'],
    'bg' => ['name' => 'Болгарский', 'native' => 'Български'],
    'bs' => ['name' => 'Боснийский', 'native' => 'Bosanski'],
    'br' => ['name' => 'Бретонский', 'native' => 'Brezhoneg'],
    'cy' => ['name' => 'Валлийский', 'native' => 'Cymraeg'],
    'wa' => ['name' => 'Валлонский', 'native' => 'Walon'],
    'hu' => ['name' => 'Венгерский', 'native' => 'Magyar'],
    've' => ['name' => 'Венда', 'native' => 'Tshivenḓa'],
    'vo' => ['name' => 'Волапюк', 'native' => 'Volapük'],
    'wo' => ['name' => 'Волоф', 'native' => 'Wolof'],
    'vi' => ['name' => 'Вьетнамский', 'native' => 'Tiếng việt'],
    'ht' => ['name' => 'Гаитянский', 'native' => 'Kreyòl ayisyen'],
    'gl' => ['name' => 'Галисийский', 'native' => 'Galego'],
    'lg' => ['name' => 'Ганда', 'native' => 'Luganda'],
    'hz' => ['name' => 'Гереро', 'native' => 'Herero'],
    'kl' => ['name' => 'Гренландский', 'native' => 'Kalaallisut'],
    'el' => ['name' => 'Греческий', 'native' => 'Ελληνικά'],
    'ka' => ['name' => 'Грузинский', 'native' => 'ქართული'],
    'gn' => ['name' => 'Гуарани', 'native' => 'Avañe’ẽ'],
    'gu' => ['name' => 'Гуджарати', 'native' => 'ગુજરાતી'],
    'gd' => ['name' => 'Гэльский', 'native' => 'Gàidhlig'],
    'da' => ['name' => 'Датский', 'native' => 'Dansk'],
    'dz' => ['name' => 'Дзонг-кэ', 'native' => 'རྫོང་ཁ'],
    'fy' => ['name' => 'Западнофризский', 'native' => 'Frysk'],
    'zu' => ['name' => 'Зулу', 'native' => 'Isizulu'],
    'he' => ['name' => 'Иврит', 'native' => 'עברית'],
    'ig' => ['name' => 'Игбо', 'native' => 'Igbo'],
    'yi' => ['name' => 'Идиш', 'native' => 'ייִדיש'],
    'io' => ['name' => 'Идо', 'native' => 'Ido'],
    'id' => ['name' => 'Индонезийский', 'native' => 'Indonesia'],
    'ia' => ['name' => 'Интерлингва', 'native' => 'Interlingua'],
    'ie' => ['name' => 'Интерлингве', 'native' => 'Interlingue'],
    'iu' => ['name' => 'Инуктитут', 'native' => 'ᐃᓄᒃᑎᑐᑦ'],
    'ik' => ['name' => 'Инупиак', 'native' => 'Inupiaq'],
    'ga' => ['name' => 'Ирландский', 'native' => 'Gaeilge'],
    'is' => ['name' => 'Исландский', 'native' => 'Íslenska'],
    'es' => ['name' => 'Испанский', 'native' => 'Español'],
    'it' => ['name' => 'Итальянский', 'native' => 'Italiano'],
    'yo' => ['name' => 'Йоруба', 'native' => 'Èdè yorùbá'],
    'kk' => ['name' => 'Казахский', 'native' => 'Қазақ тілі'],
    'kn' => ['name' => 'Каннада', 'native' => 'ಕನ್ನಡ'],
    'kr' => ['name' => 'Канури', 'native' => 'Kanuri'],
    'ca' => ['name' => 'Каталанский', 'native' => 'Català'],
    'ks' => ['name' => 'Кашмири', 'native' => 'کٲشُر'],
    'qu' => ['name' => 'Кечуа', 'native' => 'Runasimi'],
    'ki' => ['name' => 'Кикуйю', 'native' => 'Gikuyu'],
    'rw' => ['name' => 'Киньяруанда', 'native' => 'Ikinyarwanda'],
    'ky' => ['name' => 'Киргизский', 'native' => 'Кыргызча'],
    'zh' => ['name' => 'Китайский', 'native' => '中文'],
    'kv' => ['name' => 'Коми', 'native' => 'Komi'],
    'kg' => ['name' => 'Конго', 'native' => 'Kongo'],
    'ko' => ['name' => 'Корейский', 'native' => '한국어'],
    'kw' => ['name' => 'Корнский', 'native' => 'Kernewek'],
    'co' => ['name' => 'Корсиканский', 'native' => 'Corsu'],
    'xh' => ['name' => 'Коса', 'native' => 'Isixhosa'],
    'cr' => ['name' => 'Кри', 'native' => 'Cree'],
    'kj' => ['name' => 'Кунама', 'native' => 'Kuanyama'],
    'ku' => ['name' => 'Курдский', 'native' => 'Kurdî (kurmancî)'],
    'km' => ['name' => 'Кхмерский', 'native' => 'ខ្មែរ'],
    'lo' => ['name' => 'Лаосский', 'native' => 'ລາວ'],
    'la' => ['name' => 'Латинский', 'native' => 'Latina'],
    'lv' => ['name' => 'Латышский', 'native' => 'Latviešu'],
    'li' => ['name' => 'Лимбургский', 'native' => 'Limburgan'],
    'ln' => ['name' => 'Лингала', 'native' => 'Lingála'],
    'lt' => ['name' => 'Литовский', 'native' => 'Lietuvių'],
    'lu' => ['name' => 'Луба-катанга', 'native' => 'Tshiluba'],
    'lb' => ['name' => 'Люксембургский', 'native' => 'Lëtzebuergesch'],
    'mk' => ['name' => 'Македонский', 'native' => 'Македонски'],
    'mg' => ['name' => 'Малагасийский', 'native' => 'Malagasy'],
    'ms' => ['name' => 'Малайский', 'native' => 'Melayu'],
    'ml' => ['name' => 'Малаялам', 'native' => 'മലയാളം'],
    'dv' => ['name' => 'Мальдивский', 'native' => 'ދިވެހިބަސް'],
    'mt' => ['name' => 'Мальтийский', 'native' => 'Malti'],
    'mi' => ['name' => 'Маори', 'native' => 'Māori'],
    'mr' => ['name' => 'Маратхи', 'native' => 'मराठी'],
    'mh' => ['name' => 'Маршалльский', 'native' => 'Marshallese'],
    'mn' => ['name' => 'Монгольский', 'native' => 'Монгол'],
    'gv' => ['name' => 'Мэнский', 'native' => 'Gaelg'],
    'nv' => ['name' => 'Навахо', 'native' => 'Diné bizaad'],
    'na' => ['name' => 'Науру', 'native' => 'Nauru'],
    'ng' => ['name' => 'Ндонга', 'native' => 'Ndonga'],
    'de' => ['name' => 'Немецкий', 'native' => 'Deutsch'],
    'ne' => ['name' => 'Непальский', 'native' => 'नेपाली'],
    'nl' => ['name' => 'Нидерландский', 'native' => 'Nederlands'],
    'no' => ['name' => 'Норвежский', 'native' => 'Norsk'],
    'nb' => ['name' => 'Норвежский букмол', 'native' => 'Norsk bokmål'],
    'ii' => ['name' => 'Носу', 'native' => 'ꆈꌠꉙ'],
    'ny' => ['name' => 'Ньянджа', 'native' => 'Nyanja'],
    'nn' => ['name' => 'Нюнорск', 'native' => 'Norsk nynorsk'],
    'oj' => ['name' => 'Оджибва', 'native' => 'Ojibwa'],
    'oc' => ['name' => 'Окситанский', 'native' => 'Occitan'],
    'or' => ['name' => 'Ория', 'native' => 'ଓଡ଼ିଆ'],
    'om' => ['name' => 'Оромо', 'native' => 'Oromoo'],
    'os' => ['name' => 'Осетинский', 'native' => 'Ирон'],
    'pi' => ['name' => 'Пали', 'native' => 'Pali'],
    'pa' => ['name' => 'Панджаби', 'native' => 'ਪੰਜਾਬੀ'],
    'fa' => ['name' => 'Персидский', 'native' => 'فارسی'],
    'pl' => ['name' => 'Польский', 'native' => 'Polski'],
    'pt' => ['name' => 'Португальский', 'native' => 'Português'],
    'ps' => ['name' => 'Пушту', 'native' => 'پښتو'],
    'rm' => ['name' => 'Романшский', 'native' => 'Rumantsch'],
    'ro' => ['name' => 'Румынский', 'native' => 'Română'],
    'rn' => ['name' => 'Рунди', 'native' => 'Ikirundi'],
    'ru' => ['name' => 'Русский', 'native' => 'Русский'],
    'sm' => ['name' => 'Самоанский', 'native' => 'Samoan'],
    'sg' => ['name' => 'Санго', 'native' => 'Sängö'],
    'sa' => ['name' => 'Санскрит', 'native' => 'संस्कृत भाषा'],
    'sc' => ['name' => 'Сардинский', 'native' => 'Sardu'],
    'ss' => ['name' => 'Свази', 'native' => 'Siswati'],
    'se' => ['name' => 'Северносаамский', 'native' => 'Davvisámegiella'],
    'nd' => ['name' => 'Северный ндебеле', 'native' => 'Isindebele'],
    'sr' => ['name' => 'Сербский', 'native' => 'Српски'],
    'sh' => ['name' => 'Сербскохорватский', 'native' => 'Serbo-croatian'],
    'si' => ['name' => 'Сингальский', 'native' => 'සිංහල'],
    'sd' => ['name' => 'Синдхи', 'native' => 'سنڌي'],
    'sk' => ['name' => 'Словацкий', 'native' => 'Slovenčina'],
    'sl' => ['name' => 'Словенский', 'native' => 'Slovenščina'],
    'so' => ['name' => 'Сомали', 'native' => 'Soomaali'],
    'sw' => ['name' => 'Суахили', 'native' => 'Kiswahili'],
    'su' => ['name' => 'Сунданский', 'native' => 'Basa sunda'],
    'tl' => ['name' => 'Тагалог', 'native' => 'Tagalog'],
    'tg' => ['name' => 'Таджикский', 'native' => 'Тоҷикӣ'],
    'ty' => ['name' => 'Таитянский', 'native' => 'Tahitian'],
    'th' => ['name' => 'Тайский', 'native' => 'ไทย'],
    'ta' => ['name' => 'Тамильский', 'native' => 'தமிழ்'],
    'tt' => ['name' => 'Татарский', 'native' => 'Татар'],
    'tw' => ['name' => 'Тви', 'native' => 'Twi'],
    'te' => ['name' => 'Телугу', 'native' => 'తెలుగు'],
    'bo' => ['name' => 'Тибетский', 'native' => 'བོད་སྐད་'],
    'ti' => ['name' => 'Тигринья', 'native' => 'ትግርኛ'],
    'to' => ['name' => 'Тонганский', 'native' => 'Lea fakatonga'],
    'tn' => ['name' => 'Тсвана', 'native' => 'Setswana'],
    'ts' => ['name' => 'Тсонга', 'native' => 'Xitsonga'],
    'tr' => ['name' => 'Турецкий', 'native' => 'Türkçe'],
    'tk' => ['name' => 'Туркменский', 'native' => 'Türkmen dili'],
    'uz' => ['name' => 'Узбекский', 'native' => 'O‘zbek'],
    'ug' => ['name' => 'Уйгурский', 'native' => 'ئۇيغۇرچە'],
    'uk' => ['name' => 'Украинский', 'native' => 'Українська'],
    'ur' => ['name' => 'Урду', 'native' => 'اردو'],
    'fo' => ['name' => 'Фарерский', 'native' => 'Føroyskt'],
    'fj' => ['name' => 'Фиджи', 'native' => 'Fijian'],
    'fi' => ['name' => 'Финский', 'native' => 'Suomi'],
    'fr' => ['name' => 'Французский', 'native' => 'Français'],
    'ff' => ['name' => 'Фулах', 'native' => 'Pulaar'],
    'ha' => ['name' => 'Хауса', 'native' => 'Hausa'],
    'hi' => ['name' => 'Хинди', 'native' => 'हिन्दी'],
    'ho' => ['name' => 'Хиримоту', 'native' => 'Hiri motu'],
    'hr' => ['name' => 'Хорватский', 'native' => 'Hrvatski'],
    'cu' => ['name' => 'Церковнославянский', 'native' => 'Церковнослове́нскїй'],
    'ch' => ['name' => 'Чаморро', 'native' => 'Chamorro'],
    'ce' => ['name' => 'Чеченский', 'native' => 'Нохчийн'],
    'cs' => ['name' => 'Чешский', 'native' => 'Čeština'],
    'za' => ['name' => 'Чжуань', 'native' => 'Vahcuengh'],
    'cv' => ['name' => 'Чувашский', 'native' => 'Чӑваш'],
    'sv' => ['name' => 'Шведский', 'native' => 'Svenska'],
    'sn' => ['name' => 'Шона', 'native' => 'Chishona'],
    'ee' => ['name' => 'Эве', 'native' => 'Eʋegbe'],
    'eo' => ['name' => 'Эсперанто', 'native' => 'Esperanto'],
    'et' => ['name' => 'Эстонский', 'native' => 'Eesti'],
    'nr' => ['name' => 'Южный ндебеле', 'native' => 'Isindebele'],
    'st' => ['name' => 'Южный сото', 'native' => 'Sesotho'],
    'jv' => ['name' => 'Яванский', 'native' => 'Jawa'],
    'ja' => ['name' => 'Японский', 'native' => '日本語'],
];
